# docker pull onlyoffice/documentserver:latest
version: '3.2'

services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    hostname: onlyoffice
    privileged: true
    restart: always
#    network_mode: host
    networks:
      - default
    ports:
      - 8000:80
    volumes:
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24