# docker pull nginx:1.25.0
version: '3.2'
services:
  nginx:
    image: nginx:1.25.0
    container_name: nginx
    hostname: nginx
    privileged: true
    restart: always
    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/nginx/config/conf.d:/etc/nginx/conf.d
      - /home/nginx/config/mime.types:/etc/nginx/mime.types
      - /home/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - /home/nginx/html:/usr/share/nginx/html
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}