# docker pull openjdk:8-jdk-alpine
version: '3.2'

services:
  kafka:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: kafka:xtpeach
    container_name: kafka
    hostname: kafka
    privileged: true
    restart: always
    network_mode: host
    ulimits:
      nproc: 65535
      nofile:
        soft: 50000
        hard: 100000
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/kafka/conf:/usr/local/kafka_2.13-3.4.1/conf
      - /data/kafka:/data/kafka
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - BROKER_ID=0
      - LISTENERS=PLAINTEXT://192.168.96.128:9092
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181
    depends_on: []
