# docker pull bitnami/kafka:3.2.3
version: '3.2'

services:
  kafka:
    image: openjdk:8-jdk-alpine
    container_name: kafka
    hostname: kafka
    privileged: true
    restart: always
    network_mode: host
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - /data/kafka:/bitnami/kafka/data
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://192.168.96.128:9092,CONTROLLER://192.168.96.128:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.96.128:9092  # 传递回客户端的元数据，填写宿主机IP地址
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_HEAP_OPTS=-Xmx1024m -Xms1024m
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - TZ=Asia/Shanghai
    depends_on:
      - zookeeper
