# docker pull redis:6.2.12
version: '3.2'
services:
  zookeeper:
    image: zookeeper:3.7.1
    container_name: zookeeper
    hostname: zookeeper
    privileged: true
    restart: always
    network_mode: host
    ports:
      - 2181:2181
    volumes:
      - /data/zookeeper/data:/data
      - /data/zookeeper/datalog:/datalog
      - /data/zookeeper/logs:/logs
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOO_MY_ID=1 # 节点ID
      - TZ=Asia/Shanghai

  kafka:
    image: bitnami/kafka:3.2.3
    container_name: kafka
    hostname: kafka
    privileged: true
    restart: always
    network_mode: host
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - /data/kafka:/bitnami
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://0.0.0.0:9092  # 传递回客户端的元数据，填写宿主机IP地址
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_HEAP_OPTS=-Xmx1024m -Xms1024m
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - TZ=Asia/Shanghai
    depends_on:
      - zookeeper
