# docker pull postgres:14.8
version: '3.2'

services:
  postgresql:
    image: postgres:14.8
    container_name: postgresql
    hostname: postgresql
    privileged: true
    restart: always
#    network_mode: host
    networks:
      - default
    ulimits:
      nproc: 65535
      nofile:
        soft: 50000
        hard: 100000
    ports:
      - 5432:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/postgresql:/var/lib/postgresql/data
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - POSTGRES_PASSWORD=postgresql123456!
    depends_on: []

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/24