# 全局配置
global:
  scrape_interval:     15s # 将搜刮间隔设置为每15秒一次。默认是每1分钟一次。
  evaluation_interval: 15s # 每15秒评估一次规则。默认是每1分钟一次。

# 搜刮配置
scrape_configs:
  - job_name: 'prometheus'
    # 覆盖全局默认值，每15秒从该作业中刮取一次目标
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  # node
  - job_name: "node_export"
    static_configs:
      - targets:
          - "127.0.0.1:9100"

  # mysql
  - job_name: 'mysql_exporter'
    static_configs:
      - targets:
          - "127.0.0.1:9104"

  # redis
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
          - "127.0.0.1:9121"

  # kafka
  - job_name: 'kafka_exporter'
    static_configs:
      - targets:
          - "127.0.0.1:9308"

  # clickhouse
  - job_name: 'clickhouse_exporter'
    static_configs:
      - targets:
          - "127.0.0.1:9116"

  # jvm
  - job_name: 'jvm_exporter'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - "127.0.0.1:8756"