# docker pull redis:6.2.12
version: '3.2'
services:
  redis:
    image: redis:6.2.12
    container_name: redis
    hostname: redis
    privileged: true
    restart: always
    network_mode: host
    ports:
      - 6379:6379
    volumes:
      - /home/redis/conf:/usr/local/etc/redis
      - /data/redis/data:/data
    environment:
      TZ: Asia/Shanghai
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]