version: '3'

services:
  sonarqube:
    privileged: true
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    depends_on:
      - sonarqube-db
    ports:
      - "9000:9000"  # 将SonarQube应用容器的9000端口映射到主机的9000端口

  sonarqube-db:
    privileged: true
    image: postgres:latest
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /data/postgresql/data:/var/lib/postgresql/data