version: '3.3'

services:
  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    network_mode: host
    restart: always
    command: --config.my-cnf=<path_to_cnf>
